version: "3.8"

services:
  php-fpm:
    container_name: smf_php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - /var/www/vendor
      - ./../:/var/www
    networks:
      smf_net:
        ipv4_address: 10.20.0.2

  nginx:
    container_name: smf_nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm
    networks:
      smf_net:
        ipv4_address: 10.20.0.3
    
  # postgres:
  #   container_name: smf_postgres
  #   build:
  #     context: ./postgres
  #   ports:
  #     - ${POSTGRES_PORT}:5432
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   volumes:
  #     - db_data:/var/lib/postgresql/data:rw
  #   networks:
  #     smf_net:
  #       ipv4_address: 10.20.0.4
  postgis:
    container_name: smf_postgis
    build:
      context: ./postgis
    ports:
      - ${POSTGIS_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGIS_DB}
      POSTGRES_USER: ${POSTGIS_USER}
      POSTGRES_PASSWORD: ${POSTGIS_PASSWORD}
    volumes:
      - db_data_gis:/var/lib/postgresql/data:rw
    networks:
      smf_net:
        ipv4_address: 10.20.0.6
  cache:
    container_name: smf_redis
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    networks:
      smf_net:
        ipv4_address: 10.20.0.5

networks:
  smf_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/16
          gateway: 10.20.0.1

volumes:
  # db_data:
  db_data_gis:
